# Generated by Django 5.1.3 on 2024-11-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
