# Generated by Django 5.1.3 on 2024-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_transaction_biller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('bill_payment', 'Bill Payment'), ('deposit', 'Deposit')], default='transfer', max_length=20),
        ),
    ]
