# Generated by Django 5.1.3 on 2024-11-18 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Cheque Book', 'Cheque Book'), ('Account Statement', 'Account Statement'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Loan Inquiry', 'Loan Inquiry'), ('ATM Card Blocking/Replacement', 'ATM Card Blocking/Replacement'), ('Address Change', 'Address Change'), ('Transaction Limit', 'Transaction Limit')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cheque_leaves', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('new_address', models.TextField(blank=True, null=True)),
                ('new_limit', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
